#A Collection of Characters or Group of Characters within single or double qoutes.
#s="Python is a programming language and easy to programming"
#print(s)
'''sp=s.split()
print(sp)
j=" ".join(sp[::-1])
print(j)
j=" ".join(reversed(sp))
print(j)'''
'''eno=int(input("Enter Your Employee Number:"))
ename=input("Enter Your Employee Name:")
esalary=float(input("Enter Your Employee Salary:"))
eaddress=input("Enter Your Employee Address:")
print("Employee Number:{} Name:{} Salary:{} and Address:{}".format(eno,ename,esalary,eaddress))
print("Employee Number:{0} Name:{1} Salary:{2} and Address:{3}".format(eno,ename,esalary,eaddress))
print("Employee Number:{no} Name:{na} Salary:{es} and Address:{ed}".format(no=eno,na=ename,es=esalary,ed=eaddress))
print()
print("Employee Number:%i Name:%s Salary:%.2f and Address:%s" %(eno,ename,esalary,eaddress))
print()
print("Employee Number:{:d} Name:{:s} Salary:{:2.1f} and Address:{:s}".format(eno,ename,esalary,eaddress))
print("The Integral Number is:{:+d}".format(-12345))
print("The Integral Number is:{:+15d}".format(12345))
print("The Float Number is:{:21.2f}".format(12345))
print("The Binary Number is:{0:+b}".format(9))
print("The Octal Number is:{0:o}".format(-12345))
print("The Hexa Lower Number is:{:x}".format(154))
print("The Hexa Upper Number is:{0:X}".format(12345))
print("{}".format(12345))
print("{:012d}".format(12345))
print("{:010.2f}".format(12345))
print("<:{:<010d}".format(12345))
print("<:{:<010.2f}".format(12345))
print(">:{:>010d}".format(12345))
print(">:{:>010.2f}".format(12345))
print("^:{:^010d}".format(12345))
print("^:{:^010.2f}".format(12345))
print("=(+):{:=010d}".format(12345))
print("=(+):{:=010.2f}".format(12345))
print("=(-):{:=010d}".format(-12345))
print("=(-):{:=010.2f}".format(-12345))
print("{:<010s}".format("idiot"))
print("{:>010s}".format("idiot"))
print("{:^010s}".format("idiot"))
print("{::^20s}".format("idiot"))
print("{:<010}".format(12))
print("{:>010}".format(14))
print("{:^010}".format(16))
print("{::^20}".format(18))
print("{:10.3s}".format("Idiotidiot"))
print("{:<010.3s}".format("Idiotidiot"))
print("{:>010.3s}".format("Idiotidiot"))
print("{:^010.3s}".format("Idiotidiot"))
print("{:%^010.3s}".format("Idiotidiot"))
person={"age":65,"name":"idiot"}
print("My Age:{k[age]} My Name is:{k[name]}".format(k=person))
print("My Age:{age} My Name is:{name}".format(**person))
class Person:
	age=10
	name="idiot"
print("My Age:{p.age} My Name is:{p.name}".format(p=Person()))
class Person:
	def __init__(self,age,name):
		self.name=name
		self.age=age
print("My Age:{p.age} My Name is:{p.name}".format(p=Person(77,"k")))
print("My Age:{p.age} My Name is:{p.name}".format(p=Person(767,"kk")))
print("My Age:{p.age} My Name is:{p.name}".format(p=Person(7,"kkk")))
print("My Age:{p.age} My Name is:{p.name}".format(p=Person(37,"kkkkk")))
print("My Age:{p.age} My Name is:{p.name}".format(p=Person(27,"kkkk")))
print("My Age:{p.age} My Name is:{p.name}".format(p=Person(7,"kkkk")))'''