tuple=(7,9.7,True,8+9J,True,False,True)
print(type(tuple))
print(len(tuple))
print(tuple)
print(tuple[0])
print(tuple[1])
print(tuple[2])
print(tuple[3])
print(tuple.count(7))#Syntax->t.count(Exactly one value)
t=tuple.count(8)#count method is count in the tuple of values. 
print(t)
print(tuple.index(True))#To search the value and return the specified index or The value is not found Error value not in tuple.
i=tuple.index(7)#Syntax->t.index(value)
print(i)
print(dir(tuple))