#Fundamendal data types are:-
'''
1)int.
i=1
print(i)
print(type(i))
a=int(i)
print(a)
print(type(a))
b=float(i)
print(b)
print(type(b))
c=complex(i)
print(c)
print(type(c))
d=bool(i)
print(d)
print(type(d))
e=str(i)
print(e)
print(type(e))
----------------------------------------------------------
2)float.
i=1.7
print(i)
print(type(i))
a=int(i)
print(a)
print(type(a))
b=float(i)
print(b)
print(type(b))
c=complex(i)
print(c)
print(type(c))
d=bool(i)
print(d)
print(type(d))
e=str(i)
print(e)
print(type(e))
----------------------------------------------------------
3)complex.
i=8+7j
print(i)
print(type(i))
i=8-7j
print(i)
print(type(i))
i=8*7j
print(i)
print(type(i))
i=8/7j
print(i)
print(type(i))
i=8**7j
print(i)
print(type(i))
------------------
i=11/10j
print(i)
print(type(i))
j=bool(i)
print(j)
print(type(j))
----------------------------------------------------------
4)bool.
i=False
print(i)
print(type(i))
a=int(i)
print(a)
print(type(a))
b=float(i)
print(b)
print(type(b))
c=complex(i)
print(c)
print(type(c))
d=bool(i)
print(d)
print(type(d))
e=str(i)
print(e)
print(type(e))
----------------------------------------------------------
5)str.
s1=""
print(s1)
print(type(s1))
i=bool(s1)
print(i)
print(type(i))
------------------
s2='idiot'
print(s2)
print(type(s2))
j=bool(s2)
print(j)
print(type(j))
-----------------------------------------------------------
'''
"""
1)Decimal form base-10(It is default 0-9 only)
2)Binary form base-2(It is only allowed 0 and 1 prefixed with 0b or 0B)
3)Octal form base-8(0-7 only prefixed with 0o or 0O)
4)Hexa-decimal form base-16(0-9 and A-F or a-f prefixed with 0x or 0X)
"""